
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mal3abk-on-deployment
  labels:
    app: mal3abk-on
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mal3abk-on
  template:
    metadata:
      labels:
        app: mal3abk-on
    spec:
      containers:
      - name: mal3abk-on-server
        image: kimoabser/testcd:__IMAGE_TAG__
        ports:
        - containerPort: 3000
        env:
        - name: PGDATABASE
          value: "mal3abk_on"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "admin"
        - name: PGHOST
          value: "db-service"
        

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin"
            - name: POSTGRES_DB
              value: "mal3abk_on"
          ports:
            - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: mal3abk-on 
    
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000



---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
